version: 2
jobs:
  # Run st2 Unit Tests
  build:
    # 'machine' executor runs Unit tests ~x1.5 faster, comparing to 'docker' executor
    # but the fastest is still ~x1.5-2 slower, comparing to Travis
    machine: true
    parallelism: 2
    working_directory: ~/st2
    steps:
      - checkout
      - restore_cache:
          keys:
            - st2-unit-001-{{ checksum "fixed-requirements.txt" }}-{{ checksum "test-requirements.txt" }}
      - run:
          name: Prepare the environment
          command: |
            set -x
            sudo .circle/install-mongo.sh
            sudo .circle/configure-rabbitmq.sh
            sudo apt-get -qq -y install python-virtualenv python-dev
      - run:
          name: Create stanley user
          command: sudo .circle/add-itest-user.sh
      - run:
          name: Install pip requirements
          command: make requirements
      - run:
          name: Run st2 Unit Tests
          command: |
            # Workaround for table width/height used in some tests
            stty rows 50 cols 132
            make ci-unit
      - save_cache:
          key: st2-unit-001-{{ checksum "fixed-requirements.txt" }}-{{ checksum "test-requirements.txt" }}
          paths:
            - ~/.cache/pip/
            - virtualenv/

